const mainData = [{"title":"台灣環島五天四夜遊","region":"Taiwan","featured":true,"new":false,"price":"$582.00","img":"http://www.ngstravel.com/images/taiwan/TW2.jpg","link":"http://www.ngstravel.com/PDF/TW/TW5D4N2014.pdf","description":"台灣環島五天四夜遊"},
{"title":"台灣日月潭墾丁六天遊","region":"Taiwan","featured":true,"new":false,"price":"$199.00","img":"http://www.ngstravel.com/NEW_IMAGE/AS_ICON_2016/CM_TW6.jpg","link":"http://www.ngstravel.com/PDF/TW/2017/TB_TW67.pdf","description":"台灣日月潭墾丁六天遊"},
{"title":"台灣日月潭墾丁七天遊","region":"Taiwan","featured":false,"new":true,"price":"$249.00","img":"http://www.ngstravel.com/NEW_IMAGE/INDEX/TW.jpg","link":"http://www.ngstravel.com/PDF/TW/2017/TB_TW67.pdf","description":"台灣日月潭墾丁七天遊"},
{"title":"台灣日月潭墾丁八天遊","region":"Taiwan","featured":false,"new":true,"price":"$299.00","img":"http://www.ngstravel.com/NEW_IMAGE/AS_ICON_2016/CM_TW78.jpg","link":"http://www.ngstravel.com/PDF/TW/2017/TB_TW8.pdf","description":"台灣日月潭墾丁八天遊"},
{"title":"台北市區觀光","region":"Taiwan","featured":false,"new":true,"price":"$38.00","img":"http://www.ngstravel.com/images/taiwan/TW3.jpg","link":"http://www.ngstravel.com/PDF/TW/NEW/NTP_1.pdf","description":"台北市區觀光"},
{"title":"烏來原住民部落巡禮","region":"Taiwan","featured":true,"new":false,"price":"$52.00","img":"http://www.ngstravel.com/images/taiwan/TW4.jpg","link":"http://www.ngstravel.com/PDF/TW/NEW/NTP_2.pdf","description":"烏來原住民部落巡禮"},
{"title":"江南七天六晚","region":"China","featured":true,"new":false,"price":"$49.00","img":"http://www.ngstravel.com/NEW_IMAGE/2016_JN_C.jpg","link":"http://www.ngstravel.com/PDF/CHINA2017/BO_JN7D_2017.pdf","description":"江南七天六晚"},
{"title":"最美江南水鄉精品七天遊","region":"China","featured":true,"new":false,"price":"$49.00","img":"http://www.ngstravel.com/NEW_IMAGE/CHINA_ICON/2016_JN_A.jpg","link":"http://www.ngstravel.com/PDF/CHINA2017/GC_JN7D_2017.pdf","description":"最美江南水鄉精品七天遊"},
{"title":"臻品江南豪華美食八天遊","region":"China","featured":false,"new":true,"price":"$69.00","img":"http://www.ngstravel.com/NEW_IMAGE/CHINA_ICON/2016_JN8.jpg","link":"http://www.ngstravel.com/PDF/CHINA2017/GC_JN8D_2017.pdf","description":"臻品江南豪華美食八天遊"},
{"title":"乘風破浪兩天一夜","region":"US","featured":true,"new":false,"price":"$110.00","img":"http://www.ngstravel.com/images/am/AM57.jpg","link":"http://ngstravel.com/NEW_BAJA.html","description":"乘風破浪兩天一夜"},
{"title":"中部完美體驗八天風情游","region":"US","featured":true,"new":false,"price":"$684.00","img":"http://www.ngstravel.com/NEW_IMAGE/INDEX/AM_TNC8D_2016.jpg","link":"http://www.ngstravel.com/PDF/AM/AM_TNC8D2016.pdf","description":"中部完美體驗八天風情游"}];

export default mainData