const mainData = [
  {
    img: 'http://lorempixel.com/450/200/nature/1',
    link: 'http://www.google.com',
    title: 'Breakfast',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    popular: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/2',
    link: 'http://www.google.com',
    title: 'Tasty burger',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    popular: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/3',
    link: 'http://www.google.com',
    title: 'Camera',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    popular: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/4',
    link: 'http://www.google.com',
    title: 'Morning',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    popular: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/5',
    link: 'http://www.google.com',
    title: 'Hats',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    featured: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/6',
    link: 'http://www.google.com',
    title: 'Honey',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    featured: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/7',
    link: 'http://www.google.com',
    title: 'Vegetables',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    featured: true,
  },
  {
    img: 'http://lorempixel.com/450/200/nature/8',
    link: 'http://www.google.com',
    title: 'Water plant',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.',
    price: '$' + (Math.floor(Math.random() * 6) + 1) + 99,
    featured: true,
  },
];

export default mainData